### ISSUE TITLE
Setup AppVeyor for CI

### ISSUE THREAD

**Issue by omelhus** [crosscutsolutions/gremlin.linq#5]
Hey,

Should we setup AppVeyor for automatic build, test and deploy to NuGet? We can push a preview-package on commit to develop and a release package on a new tag or a commit to master.

Let me know what you think and I can set it up.

**Comment by morganarvander** [comment]
Hi! 

Fyi, I started this project with the intent on using it in a project but I had switch back to classic relational database. I ran into issues with Cosmos DB since I hit the transaction ratio limitations quite fast. So right now I'm not using this library but I plan to in the future. I guess one needs to have retries built in to the library in order to get things working properly with Cosmos DB, at least that seems to be the way to as far as I've read in the docs.

Right now, everything is built in VSTS and Nuget-packages are created and pushed to nuget.org automatically. I have also set it up so that it uses GitFlow and GitVersion. So, as soon as you tag it correctly etc according to GitFlow, there will be new Nuget packages availible a while after the CI/CD pipeline is finished.

But, we can move it to another CI/CD pipeline since I can't let you in to VSTS. If you like, your'e more than welcome to set it up on AppVeyor. Unfortunally, I can't spend any time on it right now.

**Comment by omelhus** [comment]
Alright, if you already have a flow working there's no need to switch to AppVeyor. If a GitFlow release triggers a new version, that's fine by me.

How did you manage to hit the limitations? Was it a free account with basic limitations, or an issue with scaling Cosmos DB?

I'm thinking that retries can be handled by Polly.

**Comment by morganarvander** [comment]
I used the lowest RU level (400 RU?) and realized that I needed to handle retries. I think you get a 429 result from the api and the time for retry is sent back in the headers. When I discovered this I made the decision that I wasn't going to meet the demand of time to market so I simply switched over to SQL Server and EF Core. Also, I was not happy with the performance, the queries took to long to execute and I discovered a real performance boost when switching to SQL. I don't think it was this framework slowing things down but the actual execution time of the queries.
However, I still like the idea of using a Graph database, they fit the purpose so much better than the traditional relational database. I think people tend to use relational database of plain old habit even though the graph database is a much better option.

Polly? Yes, perhaps, it would be interesting to see if it's possible. Nifty solution if so.
